name: CI Workflow with Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest tests/test_app.py

  sast-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep Scan
      run: |
        semgrep --config p/ci --sarif --output semgrep-results.sarif

    - name: Upload SARIF Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep-results.sarif

  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run OWASP Dependency-Check
      uses: dependency-check/action@v3.3.0
      with:
        output-directory: ./dependency-check-report
        format: "SARIF"

    - name: Upload SARIF Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ./dependency-check-report/dependency-check-report.sarif
