name: CI Workflow with Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pytest tests/test_app.py

  sast-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install semgrep
    - name: Run Semgrep Scan
      run: |
        semgrep --config p/ci --sarif --output semgrep-results.sarif
    - name: Upload SARIF Results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep-results.sarif

  dependency-check:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        output-directory: ./dependency-check-report
        format: "SARIF"
        fail_on_cvss: 11
    - name: Upload SARIF Results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./dependency-check-report/dependency-check-report.sarif
